-- Option 1: If table doesn't exist, create it with DELETED column
DROP TABLE HR.ITEM;
CREATE TABLE HR.ITEM (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100),
    price NUMBER,
    total_number NUMBER,
    deleted NUMBER DEFAULT 0,
    PRIMARY KEY (id)
);

-- Option 2: If table already exists, add DELETED column (run this instead if table exists)
-- ALTER TABLE HR.ITEM ADD DELETED NUMBER DEFAULT 0;
-- UPDATE HR.ITEM SET DELETED = 0 WHERE DELETED IS NULL;

-- Add unique constraint on name to prevent duplicates (optional)
-- ALTER TABLE HR.ITEM ADD CONSTRAINT item_name_unique UNIQUE (name);

SELECT * FROM HR.ITEM;
INSERT INTO HR.ITEM (name, price, total_number, deleted) VALUES ('item1', 50, 10, 0);