-- ITEM_DETAILS table: One-to-One with ITEM
-- Each row in ITEM has at most one corresponding row in ITEM_DETAILS
-- Run after ITEM table exists (database_setup.sql)

-- Oracle: "desc" is reserved, use quoted identifier
CREATE TABLE HR.ITEM_DETAILS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    item_id NUMBER NOT NULL,
    "desc" VARCHAR2(500),
    issue_date DATE,
    expiry_date DATE,
    PRIMARY KEY (id),
    CONSTRAINT fk_item_details_item FOREIGN KEY (item_id) REFERENCES HR.ITEM(id) ON DELETE CASCADE,
    CONSTRAINT uq_item_details_item_id UNIQUE (item_id)
);

-- Optional: index for JOIN performance
-- CREATE INDEX idx_item_details_item_id ON HR.ITEM_DETAILS(item_id);

SELECT * FROM HR.ITEM_DETAILS;
